# Generated by Django 3.1.6 on 2021-04-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productgallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={},
        ),
    ]
