# Generated by Django 3.1.6 on 2021-02-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(to='web.Category', verbose_name='دسته بندی'),
        ),
    ]
