# Generated by Django 3.1.6 on 2021-02-23 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210217_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان تغییر')),
                ('banner1', models.FileField(blank=True, null=True, upload_to='products/banners/', verbose_name='بنر یک')),
                ('banner2', models.FileField(blank=True, null=True, upload_to='products/banners/', verbose_name='بنر دو')),
                ('banner3', models.FileField(blank=True, null=True, upload_to='products/banners/', verbose_name='بنر سه')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-publish'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='products',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=300, unique=True, verbose_name='آدرس محصول'),
        ),
    ]
