# Generated by Django 3.1.6 on 2021-02-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210223_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='category',
            field=models.ManyToManyField(to='web.Category', verbose_name='دسته بندی'),
        ),
    ]
