# Generated by Django 3.1.6 on 2021-03-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_banners_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='category',
            field=models.ManyToManyField(blank=True, to='web.Category', verbose_name='دسته بندی'),
        ),
        migrations.CreateModel(
            name='productsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mages', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.products')),
            ],
        ),
    ]
