# Generated by Django 3.1.6 on 2021-03-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210314_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productsImage',
        ),
    ]
